export const AWS_SERVICE_DESCRIPTIONS: Record<string, string> = {
  'AWS Lambda': '서버를 관리하지 않고 이벤트나 요청에 따라 코드를 실행하는 함수형 컴퓨팅 서비스입니다.',
  'Amazon DynamoDB': '낮은 지연 시간과 자동 확장을 제공하는 완전관리형 NoSQL 데이터베이스입니다.',
  'Amazon API Gateway': 'HTTP, REST, WebSocket API를 만들고 인증, 호출 제한, 요청 라우팅을 관리하는 서비스입니다.',
  'Amazon S3': '파일과 데이터를 객체 형태로 높은 내구성으로 저장하는 스토리지 서비스입니다.',
  'Amazon SQS': '메시지를 큐에 안전하게 보관해 생산자와 소비자의 처리 시점 및 장애를 분리하는 서비스입니다.',
  'Amazon SNS': '하나의 메시지를 여러 구독자나 대상으로 동시에 전달하는 게시·구독 메시징 서비스입니다.',
  'Amazon EventBridge': 'AWS 서비스와 애플리케이션에서 발생한 이벤트를 규칙에 따라 대상으로 전달하는 이벤트 버스입니다.',
  'AWS Step Functions': '여러 작업의 실행 순서, 분기, 재시도와 오류 처리를 상태 머신으로 관리하는 워크플로 서비스입니다.',
  'Amazon Cognito': '애플리케이션 사용자를 인증하고 필요하면 AWS 리소스 접근용 임시 자격 증명도 발급하는 서비스입니다.',
  'AWS IAM': '사용자와 역할이 어떤 AWS 리소스에 어떤 작업을 수행할 수 있는지 정책으로 통제하는 서비스입니다.',
  'AWS KMS': '데이터 암호화에 사용하는 키를 생성하고 보관하며 키 사용 권한과 감사 기록을 관리하는 서비스입니다.',
  'AWS Secrets Manager': '암호, API 키, 토큰 같은 비밀 값을 암호화해 저장하고 검색 및 자동 교체하는 서비스입니다.',
  'AWS Systems Manager Parameter Store': '애플리케이션 설정값과 보안 문자열을 계층 구조로 저장하는 서비스입니다.',
  'AWS CloudFormation': '템플릿에 정의한 AWS 인프라를 일관되게 생성, 변경, 삭제하는 Infrastructure as Code 서비스입니다.',
  'AWS SAM': 'Lambda와 API Gateway 같은 서버리스 리소스를 간결한 템플릿으로 정의하고 빌드·배포하는 도구입니다.',
  'Amazon CloudWatch': 'AWS 리소스와 애플리케이션의 로그, 지표, 이벤트를 수집하고 경보를 발생시키는 모니터링 서비스입니다.',
  'AWS X-Ray': '여러 서비스에 걸친 요청의 이동 경로, 처리 시간, 오류를 추적해 병목과 장애 원인을 찾는 분산 추적 서비스입니다.',
  'AWS CloudTrail': 'AWS 계정에서 누가 언제 어떤 API를 호출했는지 기록하는 감사 서비스입니다.',
  'AWS CodePipeline': '소스 변경부터 빌드, 테스트, 승인, 배포까지 릴리스 단계를 자동화하는 CI/CD 서비스입니다.',
  'AWS CodeBuild': '소스 코드를 컴파일하고 테스트를 실행해 배포 산출물을 만드는 완전관리형 빌드 서비스입니다.',
  'AWS CodeDeploy': 'EC2, Lambda, ECS 등에 새 애플리케이션 버전을 자동으로 배포하는 서비스입니다.',
  'Amazon CloudFront': '콘텐츠를 전 세계 엣지 위치에 캐시해 사용자에게 빠르게 전달하는 CDN 서비스입니다.',
  'Amazon Kinesis': '대량의 실시간 스트리밍 데이터를 지속적으로 수집하고 처리하는 서비스입니다.',
  'Amazon ElastiCache': 'Redis 또는 Memcached 호환 인메모리 저장소를 제공해 데이터 접근 속도를 높이는 캐시 서비스입니다.',
  'Amazon EC2': '운영체제와 컴퓨팅 사양을 선택해 사용하는 가상 서버 서비스입니다.',
  'Amazon ECR': 'Docker 및 OCI 컨테이너 이미지를 저장하고 버전별로 배포하는 관리형 이미지 레지스트리입니다.',
  'Amazon ECS': '컨테이너의 배치, 실행, 확장과 상태 관리를 담당하는 컨테이너 오케스트레이션 서비스입니다.',
  'AWS STS': '역할 전환과 연동 사용자에게 제한된 수명의 임시 AWS 자격 증명을 발급하는 서비스입니다.',
  'Amazon RDS': '관계형 데이터베이스의 프로비저닝, 백업, 패치와 장애 조치를 관리하는 서비스입니다.',
  'Application Load Balancer': 'HTTP와 HTTPS 요청을 URL 경로, 호스트 이름 등의 Layer 7 규칙으로 대상에 분배하는 로드 밸런서입니다.',
  'Network Load Balancer': 'TCP, UDP, TLS 연결을 매우 낮은 지연 시간과 높은 처리량으로 분배하는 Layer 4 로드 밸런서입니다.',
};
