import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Question, QuestionAnalysis } from '../src/types';

const questions = JSON.parse(await readFile(resolve('data/dva-c02-questions.json'), 'utf8')) as Question[];
const serviceRules: [string, RegExp][] = [
  ['AWS Lambda', /Lambda/i], ['Amazon DynamoDB', /DynamoDB/i], ['Amazon API Gateway', /API Gateway/i], ['Amazon S3', /Amazon S3|S3 버킷/i], ['Amazon SQS', /SQS|Simple Queue Service/i], ['Amazon SNS', /SNS|Simple Notification Service/i], ['Amazon EventBridge', /EventBridge/i], ['AWS Step Functions', /Step Functions/i], ['Amazon Cognito', /Cognito/i], ['AWS IAM', /\bIAM\b|자격 증명|권한|역할/i], ['AWS KMS', /\bKMS\b|Key Management Service/i], ['AWS Secrets Manager', /Secrets Manager/i], ['AWS Systems Manager Parameter Store', /Parameter Store/i], ['AWS CloudFormation', /CloudFormation/i], ['AWS SAM', /\bSAM\b|Serverless Application Model/i], ['Amazon CloudWatch', /CloudWatch/i], ['AWS X-Ray', /X-Ray/i], ['AWS CloudTrail', /CloudTrail/i], ['AWS CodePipeline', /CodePipeline/i], ['AWS CodeBuild', /CodeBuild/i], ['AWS CodeDeploy', /CodeDeploy/i], ['Amazon CloudFront', /CloudFront/i], ['Amazon Kinesis', /Kinesis/i], ['Amazon ElastiCache', /ElastiCache/i], ['Amazon EC2', /\bEC2\b/i], ['Amazon ECR', /\bECR\b/i], ['Amazon ECS', /\bECS\b/i], ['AWS STS', /\bSTS\b|AssumeRole/i], ['Amazon RDS', /\bRDS\b|Aurora/i], ['Application Load Balancer', /Application Load Balancer|\bALB\b/i], ['Network Load Balancer', /Network Load Balancer|\bNLB\b/i],
];
const patterns: [string, RegExp, string][] = [
  ['Concurrency Control', /동시성|concurren/i, 'Lambda Concurrency'], ['Async Failure Handling', /비동기.*실패|실패.*비동기/i, 'Lambda Async Failure'], ['Event Source Mapping', /event source|이벤트 소스/i, 'Lambda Event Source'], ['Version / Alias', /버전|별칭|alias/i, 'Lambda Version / Alias'], ['Cold Start / Performance', /cold start|콜드 스타트|초기화 지연/i, 'Lambda Cold Start'], ['Memory / CPU', /메모리|CPU/i, 'Lambda Memory / CPU'], ['VPC Integration', /VPC.*Lambda|Lambda.*VPC/i, 'Lambda VPC Integration'], ['Execution Role', /실행 역할|execution role|Lambda.*권한|권한.*Lambda/i, 'Lambda Execution Role'],
  ['GSI vs LSI', /GSI.*LSI|LSI.*GSI|글로벌 보조.*로컬 보조/i, 'DynamoDB GSI vs LSI'], ['GSI', /GSI|글로벌 보조 인덱스/i, 'DynamoDB GSI'], ['LSI', /LSI|로컬 보조 인덱스/i, 'DynamoDB LSI'], ['Partition Key Design', /파티션 키|partition key/i, 'DynamoDB Partition Key'], ['Strong vs Eventual Consistency', /강력한 일관성|최종 일관성|eventual consistency|strong consistency/i, 'DynamoDB Consistency'], ['Streams', /DynamoDB Streams|DynamoDB 스트림/i, 'DynamoDB Streams'], ['Capacity / Throttling', /throttl|제한 조절|프로비저닝.*용량|읽기 용량|쓰기 용량/i, 'DynamoDB Capacity'], ['TTL', /\bTTL\b|Time to Live/i, 'DynamoDB TTL'], ['Transactions', /트랜잭션|Transact/i, 'DynamoDB Transactions'],
  ['Cognito User Pool', /사용자 풀|User Pool/i, 'Cognito User Pool'], ['Cognito Identity Pool', /자격 증명 풀|Identity Pool/i, 'Cognito Identity Pool'], ['AssumeRole / STS', /AssumeRole|Security Token Service|\bSTS\b/i, 'Cross-account Role Assumption'], ['Cross-account Access', /교차 계정|다른 AWS 계정|여러 AWS 계정/i, 'Cross-account Access'], ['Secrets Manager', /Secrets Manager/i, 'Secrets Management'], ['Parameter Store', /Parameter Store/i, 'Configuration and Secrets'], ['KMS', /\bKMS\b|Key Management Service/i, 'Encryption with KMS'], ['IAM Role', /IAM 역할|IAM role/i, 'IAM Role and Permissions'], ['Resource Policy', /리소스 기반 정책|resource-based policy|리소스 정책/i, 'Resource-based Access'],
  ['SQS Decoupling', /분리|decoupl|SQS 큐/i, 'SQS Decoupling'], ['SNS Fan-out', /fan.?out|팬아웃|여러.*구독/i, 'SNS Fan-out'], ['DLQ', /DLQ|dead.?letter|배달 못한 편지/i, 'Dead-letter Queue'], ['Visibility Timeout', /가시성 제한|visibility timeout/i, 'SQS Visibility Timeout'], ['FIFO', /\bFIFO\b|순서.*중복/i, 'FIFO Ordering and Deduplication'], ['EventBridge Routing', /EventBridge.*규칙|이벤트 버스|event bus/i, 'EventBridge Routing'], ['EventBridge Scheduling', /예약.*EventBridge|EventBridge.*예약|schedule/i, 'EventBridge Scheduling'], ['Event Filtering', /이벤트 필터|event filtering|필터 패턴/i, 'Event Filtering'], ['Kinesis', /Kinesis/i, 'Kinesis Streaming'], ['Step Functions', /Step Functions|상태 머신|워크플로/i, 'Workflow Orchestration'],
  ['Authorizer', /authorizer|권한 부여자/i, 'API Gateway Authorization'], ['Cognito', /Cognito/i, 'API Authentication with Cognito'], ['API Key / Usage Plan', /API 키|사용 계획|usage plan/i, 'API Usage Control'], ['Canary Deployment', /카나리|canary/i, 'Canary Deployment'], ['Mapping Template', /매핑 템플릿|mapping template/i, 'API Request Transformation'], ['Stage / Stage Variable', /스테이지 변수|stage variable/i, 'API Stage Configuration'], ['Lambda Integration', /API Gateway.*Lambda|Lambda.*API Gateway/i, 'API Gateway Lambda Integration'],
  ['Change Set', /변경 세트|change set/i, 'CloudFormation Change Set'], ['Drift Detection', /드리프트|drift/i, 'CloudFormation Drift'], ['ImportValue', /ImportValue|내보낸 값|export.*stack/i, 'Cross-stack Reference'], ['DeletionPolicy', /DeletionPolicy|삭제 정책/i, 'CloudFormation Resource Retention'], ['SAM Transform', /SAM Transform|Transform.*Serverless/i, 'SAM Template'], ['Deployment Package', /\bSAM\b.*(?:빌드|패키징|배포)|(?:빌드|패키징|배포).*\bSAM\b/i, 'SAM Build / Package / Deploy'], ['Dynamic Reference', /동적 참조|dynamic reference/i, 'CloudFormation Dynamic Reference'],
  ['X-Ray', /X-Ray|분산 추적/i, 'Distributed Tracing'], ['CloudTrail', /CloudTrail/i, 'API Audit Trail'], ['Metric Filter', /지표 필터|metric filter/i, 'CloudWatch Metric Filter'], ['Custom Metric', /사용자 지정 지표|custom metric/i, 'CloudWatch Custom Metric'], ['Alarm', /CloudWatch.*경보|경보.*CloudWatch/i, 'CloudWatch Alarm'], ['CloudWatch Logs', /CloudWatch Logs|로그 그룹|로그 스트림/i, 'CloudWatch Logging'],
  ['CodePipeline', /CodePipeline/i, 'CI/CD Pipeline'], ['CodeBuild Cache', /CodeBuild.*캐시|캐시.*CodeBuild/i, 'CodeBuild Cache'], ['CodeBuild', /CodeBuild/i, 'Build Automation'], ['CodeDeploy', /CodeDeploy/i, 'Deployment Automation'], ['Blue/Green', /blue.?green|블루.?그린/i, 'Blue/Green Deployment'], ['Rollback', /롤백|rollback/i, 'Deployment Rollback'],
  ['Presigned URL', /미리 서명|presigned/i, 'S3 Presigned URL'], ['S3 Event', /S3 이벤트|객체.*생성.*이벤트/i, 'S3 Event Notification'], ['S3 Access', /S3.*접근|S3.*권한|버킷 정책/i, 'S3 Access Control'], ['CloudFront Cache', /CloudFront.*캐시|캐시.*CloudFront/i, 'CloudFront Caching'], ['OAC', /Origin Access Control|\bOAC\b/i, 'CloudFront Origin Access'], ['ElastiCache', /ElastiCache/i, 'Application Caching'], ['VPC Endpoint', /VPC 엔드포인트|VPC endpoint/i, 'Private Service Access'], ['X-Forwarded-For', /X-Forwarded-For|클라이언트 IP.*HTTP|HTTP.*클라이언트 IP/i, 'ALB Client IP Forwarding'],
];
const partFor = (services: string[], pattern: string) => pattern.startsWith('Lambda') || services.includes('AWS Lambda') ? 'PART 1 Lambda' : pattern.startsWith('DynamoDB') || services.includes('Amazon DynamoDB') ? 'PART 2 DynamoDB' : services.some((s) => ['Amazon API Gateway','Amazon S3','Amazon CloudFront'].includes(s)) ? 'PART 3 API Gateway + S3' : services.some((s) => ['Amazon SQS','Amazon SNS','Amazon EventBridge','Amazon Kinesis','AWS Step Functions'].includes(s)) ? 'PART 4 Messaging / Event' : services.some((s) => ['AWS IAM','AWS KMS','AWS Secrets Manager','AWS Systems Manager Parameter Store','Amazon Cognito','AWS STS'].includes(s)) ? 'PART 5 Security' : services.some((s) => ['AWS CloudFormation','AWS SAM','AWS CodePipeline','AWS CodeBuild','AWS CodeDeploy'].includes(s)) ? 'PART 6 IaC / CI-CD' : services.some((s) => ['Amazon CloudWatch','AWS X-Ray','AWS CloudTrail'].includes(s)) ? 'PART 7 Observability / Troubleshooting' : 'PART 8 Other Services';
const sentences = (text: string) => text.split(/(?<=[.!?다])\s+/).map((s) => s.trim()).filter((s) => s.length > 15);
const conceptExplanationFor = (concept: string, explanationSentences: string[]) => {
  if (concept === 'ALB Client IP Forwarding') return 'X-Forwarded-For는 HTTP 프록시나 로드 밸런서를 거치기 전 원래 클라이언트 IP를 전달하는 HTTP 헤더다. ALB는 Layer 7에서 요청을 종료하고 백엔드로 새 연결을 만들기 때문에 애플리케이션이 source IP만 보면 ALB 주소를 보게 된다. 따라서 ALB가 추가한 X-Forwarded-For 값을 읽어야 실제 클라이언트 IP를 얻을 수 있다.';
  if (concept === 'Lambda Execution Role') return 'Lambda 실행 역할은 함수가 실행 중 다른 AWS 서비스를 호출할 권한을 제공하는 IAM 역할이다. 함수 호출이 성공했더라도 DynamoDB PutItem 같은 후속 API 권한이 없으면 해당 작업만 AccessDenied로 실패할 수 있다.';
  if (concept === 'Secrets Management') return 'Secrets Manager는 토큰과 암호 같은 비밀 값을 KMS로 암호화해 저장하고 TLS로 전달한다. 고객 관리형 KMS 키와 시크릿 리소스 정책을 조합하면 교차 계정 접근도 명시적으로 제어할 수 있다.';
  if (concept === 'Workflow Orchestration') return 'Step Functions는 작업 순서, 분기, 재시도와 오류 처리를 상태 머신으로 관리한다. 개별 Lambda를 직접 연결하는 방식보다 실행 흐름과 실패 복구가 명시적이다.';
  return explanationSentences.filter((s) => !/^정답은?\s*[A-F]/.test(s)).slice(0, 2).join(' ') || `${concept}은 문제의 요구사항과 정답을 연결하는 핵심 DVA-C02 개념이다.`;
};
const serviceDescriptions: Record<string, string> = {
  'AWS Lambda': '서버를 관리하지 않고 이벤트나 요청에 따라 코드를 실행하는 함수형 컴퓨팅 서비스', 'Amazon DynamoDB': '낮은 지연 시간과 자동 확장을 제공하는 관리형 NoSQL 데이터베이스', 'Amazon API Gateway': 'HTTP·REST·WebSocket API를 생성하고 인증, 제한, 라우팅을 관리하는 서비스', 'Amazon S3': '객체를 내구성 높게 저장하고 이벤트·정적 콘텐츠·데이터 레이크에 사용하는 스토리지', 'Amazon SQS': '생산자와 소비자를 분리하고 메시지를 안정적으로 보관하는 큐 서비스', 'Amazon SNS': '하나의 메시지를 여러 구독자에게 전달하는 게시·구독 서비스', 'Amazon EventBridge': 'AWS 서비스와 애플리케이션 이벤트를 규칙에 따라 대상으로 라우팅하는 이벤트 버스', 'AWS Step Functions': '여러 작업의 순서, 분기, 재시도와 오류 처리를 상태 머신으로 조정하는 서비스', 'Amazon Cognito': '애플리케이션 사용자 인증과 임시 AWS 자격 증명 발급을 제공하는 서비스', 'AWS IAM': 'AWS 리소스에 누가 어떤 작업을 할 수 있는지 정책으로 통제하는 권한 서비스', 'AWS KMS': '암호화 키 생성과 사용 권한을 중앙 관리하는 서비스', 'AWS Secrets Manager': '암호·토큰 같은 비밀 값을 암호화해 저장하고 검색·교체하는 서비스', 'AWS Systems Manager Parameter Store': '설정값과 보안 문자열을 계층적으로 저장하는 서비스', 'AWS CloudFormation': '템플릿으로 AWS 인프라를 생성하고 변경하는 IaC 서비스', 'AWS SAM': '서버리스 애플리케이션을 간결한 템플릿으로 정의·빌드·배포하는 도구', 'Amazon CloudWatch': '로그, 지표, 경보를 수집해 애플리케이션 상태를 관찰하는 서비스', 'AWS X-Ray': '분산 요청 경로와 지연·오류를 추적하는 서비스', 'AWS CloudTrail': 'AWS 계정의 API 호출과 사용자 활동을 감사 로그로 기록하는 서비스', 'AWS CodePipeline': '소스부터 빌드·테스트·배포까지 릴리스 단계를 자동화하는 서비스', 'AWS CodeBuild': '소스 코드를 컴파일하고 테스트해 배포 산출물을 만드는 관리형 빌드 서비스', 'AWS CodeDeploy': 'EC2·Lambda·ECS 등에 애플리케이션 버전을 자동 배포하는 서비스', 'Amazon CloudFront': '전 세계 엣지에서 콘텐츠를 캐시하고 전달하는 CDN', 'Amazon Kinesis': '대규모 실시간 스트리밍 데이터를 수집하고 처리하는 서비스', 'Amazon ElastiCache': 'Redis 또는 Memcached 기반 인메모리 캐시 서비스', 'Amazon EC2': '가상 서버 인스턴스를 제공하는 컴퓨팅 서비스', 'Amazon ECR': '컨테이너 이미지를 저장하고 배포하는 관리형 레지스트리', 'Amazon ECS': '컨테이너 실행과 배치를 관리하는 오케스트레이션 서비스', 'AWS STS': '제한된 수명의 임시 AWS 자격 증명을 발급하는 서비스', 'Amazon RDS': '관계형 데이터베이스의 운영과 백업을 관리하는 서비스', 'Application Load Balancer': 'HTTP/HTTPS 요청을 경로·호스트 규칙으로 분배하는 Layer 7 로드 밸런서', 'Network Load Balancer': 'TCP/UDP/TLS 연결을 높은 처리량으로 분배하는 Layer 4 로드 밸런서',
};
const analyses: Record<string, QuestionAnalysis> = {};
for (const q of questions) {
  const all = `${q.question} ${q.choices.map((c) => c.text).join(' ')} ${q.explanation ?? ''}`; const correctText = q.choices.filter((c) => q.correctAnswers.includes(c.key)).map((c) => c.text).join(' '); const serviceScore = ([, re]: [string, RegExp]) => (re.test(correctText) ? 6 : 0) + (re.test(q.question) ? 3 : 0) + (re.test(q.explanation ?? '') ? 1 : 0) + (re.test(all) ? .1 : 0); const primaryServices = serviceRules.filter((rule) => serviceScore(rule) >= 3).sort((a, b) => serviceScore(b) - serviceScore(a)).map(([name]) => name); const secondaryServices = serviceRules.filter((rule) => serviceScore(rule) < 3 && serviceScore(rule) > 0).sort((a, b) => serviceScore(b) - serviceScore(a)).map(([name]) => name);
  const patternScore = ([, re]: [string, RegExp, string]) => (re.test(correctText) ? 6 : 0) + (re.test(q.question) ? 3 : 0) + (re.test(q.explanation ?? '') ? 1 : 0); const matched = patterns.map((rule) => ({ rule, score: patternScore(rule) })).sort((a, b) => b.score - a.score)[0]; const problemPattern = matched?.score ? matched.rule[0] : 'OTHER'; const concept = matched?.score ? matched.rule[2] : `${primaryServices[0] ?? 'AWS'} Architecture Decision`; const explanationSentences = sentences(q.explanation ?? '');
  const clueCandidates = sentences(q.question).filter((s) => /해야|요구|가장|최소|오류|실패|보안|확장|지연|비용|계정|권한|이벤트|동시|캐시|암호|배포/.test(s)); const keyClues = (clueCandidates.length ? clueCandidates : sentences(q.question)).slice(-3);
  const distractorAnalysis = q.choices.filter((c) => !q.correctAnswers.includes(c.key)).map((c) => ({ choice: c.key, concept: serviceRules.find(([, re]) => re.test(c.text))?.[0] ?? 'Alternative approach', whyWrong: explanationSentences.find((s) => s.includes(c.key) || c.text.split(/\s+/).slice(0, 3).some((word) => word.length > 3 && s.includes(word))) ?? `이 선택지는 핵심 요구사항(${keyClues[0] ?? '문제 조건'})을 정답만큼 직접 충족하지 못한다.` }));
  const architecturePath = primaryServices.slice(0, 5); const answerRule = concept === 'ALB Client IP Forwarding' ? 'HTTP/HTTPS + 원본 클라이언트 IP 필요 = Layer 7 ALB가 삽입하는 X-Forwarded-For를 애플리케이션에서 읽는다. NLB의 X-Forwarded-For 조합은 맞지 않으며 프록시 프로토콜은 별도 구성이 필요하다.' : explanationSentences.find((sentence) => !/^정답은?\s*[A-F]/.test(sentence) && /때문|따라서|지원|제공|작동|충족|적합/.test(sentence)) ?? explanationSentences[0] ?? `핵심 요구사항과 ${correctText}의 기능을 연결한다.`;
  analyses[String(q.originalNumber)] = { domain: 'Development with AWS Services', part: partFor(primaryServices, concept), primaryServices: primaryServices.slice(0, 3), secondaryServices: [...primaryServices.slice(3), ...secondaryServices], concept, problemPattern, ...(problemPattern === 'OTHER' ? { suggestedPattern: concept } : {}), architecturePath, keyClues, decisionPoint: keyClues[0] ? `이 요구사항을 가장 직접적으로 충족하는 AWS 기능은 무엇인가? (${keyClues[0]})` : '핵심 요구사항을 어느 AWS 기능이 직접 충족하는가?', reasoningPath: [`문제에서 핵심 단서와 제약을 식별한다: ${keyClues.join(' / ')}`, `관련 서비스를 후보로 좁힌다: ${primaryServices.join(', ') || 'AWS managed service'}`, `정답 선지가 요구사항을 직접 충족하는지 확인한다: ${correctText}`, '나머지 선지가 요구사항을 누락하거나 불필요한 운영 오버헤드를 만드는지 제거한다.', `원본 정답 ${q.correctAnswers.join(', ')}를 선택하고 해설의 근거와 대조한다.`], correctAnswerRule: answerRule, examTrap: distractorAnalysis.slice(0, 3).map((d) => d.concept).join(' vs ') || 'Similar AWS features', distractorAnalysis, difficulty: Math.min(5, Math.max(1, 2 + (primaryServices.length >= 3 ? 1 : 0) + (q.choices.length > 4 ? 1 : 0))) as 1|2|3|4|5 };
  analyses[String(q.originalNumber)].conceptExplanation = conceptExplanationFor(concept, explanationSentences);
  analyses[String(q.originalNumber)].serviceSummaries = Object.fromEntries([...primaryServices, ...secondaryServices].map((service) => [service, serviceDescriptions[service] ?? `${service}는 이 문제의 아키텍처 또는 선택지 판단에 사용되는 AWS 서비스다.`]));
}
await mkdir(resolve('public/local-data'), { recursive: true }); await writeFile(resolve('public/local-data/dva-c02-analysis.json'), JSON.stringify({ source: 'dva-c02-full-553.pdf', generatedAt: new Date().toISOString(), analyses }, null, 2)); console.log(`Generated ${Object.keys(analyses).length} local analyses.`);
